fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
  symlinks:
    ec2tagfacts: "#{source_dir}"
